KingBugTracker/Models/Attachment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KingBugTracker.Models
{
    public class Attachment
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        [Required]
        public string Body { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy}")]
        public DateTimeOffset Created { get; set; }
        public string AuthorUserId { get; set; }
        public string FileUrl { get; set; }
        public string FileDisplayName { get; set; }

        public virtual KingBugTracker.Models.ApplicationUser AuthorUser { get; set; }

        public virtual KingBugTracker.Models.Ticket Ticket { get; set; }
    }
}

KingBugTracker/Controllers/AttachmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingBugTracker.Models;
using KingBugTracker.Models.Helpers;
using System.IO;
using Microsoft.AspNet.Identity;

namespace KingBugTracker.Controllers
{
    public class AttachmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Attachments
        public ActionResult Index()
        {
            var attachments = db.Attachments.Include(a => a.AuthorUser).Include(a => a.Ticket);
            return View(attachments.ToList());
        }

        // GET: Attachments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = db.Attachments.Find(id);
            if (attachment == null)
            {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // GET: Attachments/Create
        public ActionResult Create(int id)
        {
            ViewBag.TicketId = id;
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName");
            //ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title");
            return View();
        }

        // POST: Upload
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TicketId,Body,Created,AuthorUserId,FileUrl,FileDisplayName")] Attachment attachment, HttpPostedFileBase image, int id)
        {
            if (ModelState.IsValid)
            {
                if (image != null && image.ContentLength > 0)
                {
                    string userId = User.Identity.GetUserId();
                    attachment.AuthorUserId = userId;
                    attachment.Created = DateTimeOffset.Now;
                    attachment.TicketId = id;
                    var ext = Path.GetExtension(image.FileName).ToLower();
                    if (ext != ".png" && ext != ".jpg" && ext != ".jpeg" && ext != ".gif" && ext != ".gif" && ext != ".bmp" && ext != ".docx" && ext != ".pdf" && ext != ".txt")
                    {
                        ModelState.AddModelError("image", "Invalid Format.");
                    }
                    if (image != null)
                    {
                        var fileName = Path.GetFileName(image.FileName);
                        image.SaveAs(Path.Combine(Server.MapPath("~/File Uploads/"), fileName));
                        attachment.FileUrl = "/File Uploads/" + fileName;
                        attachment.FileDisplayName = fileName;
                    }
                }
                db.Attachments.Add(attachment);
                Ticket ticket = new Ticket();
                ticket = db.Tickets.Find(attachment.TicketId);
                //Ticket oldTicket = new ApplicationDbContext().Tickets.Find(ticket.Id);
                //var history = new History
                //{
                //    ChangeDate = new DateTimeOffset(DateTime.Now),
                //    TicketId = ticket.Id,
                //    UserId = User.Identity.GetUserId(),
                //    Property = "Type",
                //    OldValue = oldTicket.Type.Name,
                //    NewValue = db.Types.Find(ticket.TypeId).Name
                //};
                //db.Histories.Add(history);
                if (ticket.AssignedToUserId != null)
                {
                    var notify = new Notification
                    {
                        TicketId = ticket.Id,
                        Message = "An Attachment has been made for " + ticket.Title,
                        Type = "Attachment",
                        ChangeDate = DateTimeOffset.Now,
                        NotifyUserId = ticket.AssignedToUserId
                    };
                    db.Notifications.Add(notify);
                }

                db.SaveChanges();
                //return RedirectToAction("Index");
                return RedirectToAction("Details", "Tickets", new { id = attachment.TicketId});

            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", attachment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", attachment.TicketId);
            //return View(attachment);
            return RedirectToAction("Details", "Tickets", new { id = attachment.TicketId });


        }
        // GET: Attachments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = db.Attachments.Find(id);
            if (attachment == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", attachment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", attachment.TicketId);
            return View(attachment);
        }

        // POST: Attachments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TicketId,Body,Created,AuthorUserId,FileUrl,FileDisplayName")] Attachment attachment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(attachment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", attachment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", attachment.TicketId);
            return View(attachment);
        }

        // GET: Attachments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attachment attachment = db.Attachments.Find(id);
            if (attachment == null)
            {
                return HttpNotFound();
            }
            return View(attachment);
        }

        // POST: Attachments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Attachment attachment = db.Attachments.Find(id);
            db.Attachments.Remove(attachment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

KingBugTracker/Views/Attachments/Create.cshtml
@model KingBugTracker.Models.Attachment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Attachments", FormMethod.Post, new { enctype = "Multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="tId" value="@ViewBag.TicketId" />

    <div class="form-horizontal">
        <h4>Attachment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.TicketId)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.AuthorUser)
        @Html.HiddenFor(model => model.FileUrl)*@




        @*<div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.AuthorUserId, "AuthorUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorUserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <input name="image" type="file" class="form-control" id="fileUpload" />
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FileDisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileDisplayName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileDisplayName, "", new { @class = "text-danger" })
            </div>
        </div>
        <input name="image" type="file" class="form-control" id="fileLoaded" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KingBugTracker/Views/Attachments/Delete.cshtml
@model KingBugTracker.Models.Attachment

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attachment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileDisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileDisplayName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KingBugTracker/Views/Attachments/Details.cshtml
@model KingBugTracker.Models.Attachment

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Attachment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ticket.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ticket.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileDisplayName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileDisplayName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KingBugTracker/Views/Attachments/Edit.cshtml
@model KingBugTracker.Models.Attachment

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Tickets", FormMethod.Post, new { entype = "Multipart/form-date"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attachment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.TicketId)
        @Html.HiddenFor(model => model.Created)
        @Html.HiddenFor(model => model.AuthorUser)
        @Html.HiddenFor(model => model.FileUrl)


        @*<div class="form-group">
            @Html.LabelFor(model => model.TicketId, "TicketId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TicketId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AuthorUserId, "AuthorUserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AuthorUserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AuthorUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileUrl, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FileDisplayName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileDisplayName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileDisplayName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KingBugTracker/Views/Attachments/Index.cshtml
@model IEnumerable<KingBugTracker.Models.Attachment>

@{
    ViewBag.Title = "Index";
}
        <h2>Index</h2>

        <p>
            @Html.ActionLink("Create New", "Create")
        </p>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ticket.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Body)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Created)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FileUrl)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FileDisplayName)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AuthorUser.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ticket.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Body)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Created)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileUrl)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FileDisplayName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }

        </table>