KingBugTracker/Models/Helpers/ProjectAssignHelper.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using KingBugTracker.Models;

namespace KingBugTracker.Models
{
    public class ProjectAssignHelper
    {
        private ApplicationDbContext db;

        public ProjectAssignHelper(ApplicationDbContext context)
        {
            //this.userManager = new UserManager<ApplicationUser>(
            //    new UserStore<ApplicationUser>(context));
            //this.roleManager = new RoleManager<IdentityRole>(
            //    new RoleStore<IdentityRole>(context));
            this.db = context;
        }

        public bool IsProjectOnUser(int projectId, string userId)
        {
            var project = db.Projects.Find(projectId);
            var userCheck = project.Users.Any(p => p.Id == userId);
            return (userCheck);
        }

        //public string GetUserInRole(string userId)
        //{
        //    return userManager.GetRoles(userId).First();
        //}

        //public IList<string> ListAssignedUsers(int projectId)
        public ICollection<ApplicationUser> ListAssignedUsers(int projectId)
        {
            Project project = db.Projects.Find(projectId);
            var userList = project.Users.ToList();
            return (userList);
        }

        public bool AddProjectToUser(int projectId, string userId)
        {
            Project project = db.Projects.Find(projectId);
            ApplicationUser user = db.Users.Find(userId);

            project.Users.Add(user);

            try
            {
                var userAdded = db.SaveChanges();

                if (userAdded != 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch
            {
                return false;
            }

            //var roles = userManager.GetRoles(userId);
            //foreach(var role in roles)
            //{
            //    RemoveUserFromRole(userId, role);
            //}
            //var result = userManager.AddToRole(projectId, userId);
            //return result.Succeeded;
        }

        public bool RemoveProjectFromUser(int projectId, string userId)
        {
            Project project = db.Projects.Find(projectId);
            ApplicationUser user = db.Users.Find(userId);

            var result = project.Users.Remove(user);

            try
            {
                var userRemoved = db.SaveChanges();

                if (userRemoved != 0)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch
            {
                return false;
            }

            //var result = userManager.RemoveFromRole(projectId, userId);
            //return result.Succeeded;
        }

        //NEEDED?
        //public IList<ApplicationUser> UsersInRole(string roleName)
        //{
        //    var userIDs = roleManager.FindByName(roleName).Users.Select(r => r.UserId);
        //    return userManager.Users.Where(u => userIDs.Contains(u.Id)).ToList();
        //    //Select(u => new UserDropDownViewModel { Id = u.Id, Name = u.DisplayName }).
        //}

        //NEEDED?
        //public IList<ApplicationUser> UsersNotInRole(string roleName)
        //{
        //    var userIDs = System.Web.Security.Roles.GetUsersInRole(roleName);
        //    return userManager.Users.Where(u => !userIDs.Contains(u.Id)).ToList();
        //    //Select(u => new UserDropDownViewModel { Id = u.Id, Name = u.DisplayName }).
        //}

        //public IList<string> ListUserRoles(string userId)
        //{
        //    return manager.GetRoles(userId);
        //}

        //public bool AddUserToRole(string userId, string roleName)
        //{
        //    var result = manager.AddToRole(userId, roleName);
        //    return result.Succeeded;
        //}

        //public bool RemoveUserFromRole(string userId, string roleName)
        //{
        //    var result = manager.RemoveUserFromRole(string userId, string roleName);
        //    return result.Succeeded;
        //}
    }
}

KingBugTracker/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KingBugTracker.Models
{
    public class Project
    {
        public Project()
        {
            this.Tickets = new HashSet<KingBugTracker.Models.Ticket>();
            this.Users = new HashSet<KingBugTracker.Models.ApplicationUser>();
        }

        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Body { get; set; }
        public bool IsDeleted { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy}")]
        public DateTimeOffset Created { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy}")]
        public DateTimeOffset? Updated { get; set; }
        public virtual ICollection<ApplicationUser> Users { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}

KingBugTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingBugTracker.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;

namespace KingBugTracker.Controllers
{
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ProjectAssignHelper projectHelper;
        private UserRolesHelper roleHelper;

        public ProjectsController()
        {
            projectHelper = new ProjectAssignHelper(db);
            roleHelper = new UserRolesHelper(db);
        }
        // GET: Projects
        public ActionResult Index()
        {

            return View();
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }


        // GET: Projects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,Created,Updated,Users")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.Created = new DateTimeOffset(DateTime.Now);

                //project.Users.Add(db.Users.First());
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,Created,Updated")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.Updated = new DateTimeOffset(DateTime.Now);
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View(project);
        }
        
        //Get
        [Authorize(Roles = "Admin, Project Manager, Guest")]
        public ActionResult ProjectAssign(int id)
        {
            var project = db.Projects.Find(id);
            ProjectAssignHelper helper = new ProjectAssignHelper(db);
            var model = new ProjectAssignUsersViewModel();

            model.Project = project;
            model.SelectedUsers = helper.ListAssignedUsers(id).Select(u => u.Id).ToArray();
            model.Users = new MultiSelectList(db.Users.Where(u => (u.DisplayName != "N/A" && u.DisplayName != "(Remove Assign User)")).OrderBy(u => u.FirstName), "Id", "DisplayName", model.SelectedUsers);
            return View(model);
        }

        //Post
        [HttpPost]
        [Authorize(Roles = "Admin, Project Manager, Guest")]
        public ActionResult ProjectAssign(ProjectAssignUsersViewModel model)
        {
            var project = db.Projects.Find(model.Project.Id);
            ProjectAssignHelper helper = new ProjectAssignHelper(db);

            foreach (var user in db.Users.Select(r => r.Id).ToList())
            {
                helper.RemoveProjectFromUser(project.Id, user);
            }
            if (model.SelectedUsers != null)
            {
                foreach (var user in model.SelectedUsers)
                {
                    helper.AddProjectToUser(project.Id, user);
                }
            }
            return RedirectToAction("Index", "Home");
        }


        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            var project  = db.Projects.Find(id);
            var tickets = db.Tickets.Where(t => t.Status.Name != "Closed" && t.ProjectId == id).ToList();


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            if (tickets.Count > 0)
            {
                project.Tickets = tickets;
                return View(project);
            }
            else
            {
                project.IsDeleted = true;
                //db.Projects.Remove(project);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");

            }
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            project.IsDeleted = true;
            //db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KingBugTracker/Views/Projects/Create.cshtml
@model KingBugTracker.Models.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Updated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Updated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Updated, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

KingBugTracker/Views/Projects/Delete.cshtml
@model KingBugTracker.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Inactivate" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Home")
        </div>
    }
</div>

KingBugTracker/Views/Projects/Details.cshtml
@model KingBugTracker.Models.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>
        <dt>
            Users Assigned
        </dt>
        <dd>
            @foreach (var name in Model.Users)
            {
                @name.DisplayName
                <br />
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", "Home", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", "Home")
</p>

KingBugTracker/Views/Projects/Edit.cshtml
@model KingBugTracker.Models.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "BlogPosts", FormMethod.Post, new { enctype = "Multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Updated)


        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>*@

   
        @*  <div class="form-group">
            @Html.LabelFor(model => model.Updated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Updated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Updated, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

KingBugTracker/Views/Projects/Index.cshtml
@model IEnumerable<KingBugTracker.Models.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Body)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Body)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Updated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

KingBugTracker/Views/Projects/ProjectAssign.cshtml
@model KingBugTracker.Models.ProjectAssignUsersViewModel

@{
	ViewBag.Title = "Project Assignment";
}

@using (Html.BeginForm("ProjectAssign", "Projects", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
<div>
	<strong>Project Name</strong><br />
	@Model.Project.Title
	<br />
	@Html.HiddenFor(model => model.Project.Id, new { })
	<br />
	@Html.ListBox("SelectedUsers", Model.Users, htmlAttributes: new { id = "mySelect" })

	<br />
	<br />
	<button class="btn btn-default" type="submit">Assign Users</button>
</div>
}

<a class="btn btn-default" href="@Url.Action(" Index", "Home" )">Back to List</a>