KingBugTracker/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KingBugTracker.Models
{
    public class Ticket
    {
        public Ticket()
        {
            this.Comments = new HashSet<Comment>();
            this.Attachments = new HashSet<Attachment>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        [Required]
        public string Body { get; set; }
        public bool IsDeleted { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy}")]
        public DateTimeOffset Created { get; set; }
        [DisplayFormat(DataFormatString = "{0:M/d/yyyy}")]
        public DateTimeOffset? Updated { get; set; }
        public int ProjectId { get; set; }
        public int TypeId { get; set; }
        public int PriorityId { get; set; }
        public int StatusId { get; set; }

        public string AuthorUserId { get; set; }
        public string AssignedToUserId { get; set; }

        public virtual KingBugTracker.Models.Type Type { get; set; }
        public virtual KingBugTracker.Models.Priority Priority { get; set; }
        public virtual KingBugTracker.Models.Status Status { get; set; }

        public virtual KingBugTracker.Models.ApplicationUser AuthorUser { get; set; }
        public virtual KingBugTracker.Models.ApplicationUser AssignedToUser { get; set; }
        public virtual KingBugTracker.Models.Project Project { get; set; }

        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<History> Histories { get; set; }
    }
}

KingBugTracker/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingBugTracker.Models;
using Microsoft.AspNet.Identity;

namespace KingBugTracker.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.AuthorUser).Include(c => c.Ticket);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Body,Created,Updated,TicketId,AuthorUserId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.AuthorUserId = User.Identity.GetUserId();
                comment.Created = new DateTimeOffset(DateTime.Now);
                Ticket ticket = new Ticket();
                //Ticket oldTicket = new ApplicationDbContext().Tickets.Find(ticket.Id);
                ticket = db.Tickets.Find(comment.TicketId);
                //var history = new History
                //{
                //    ChangeDate = new DateTimeOffset(DateTime.Now),
                //    TicketId = ticket.Id,
                //    UserId = User.Identity.GetUserId(),
                //    Property = "Type",
                //    OldValue = oldTicket.Type.Name,
                //    NewValue = db.Types.Find(ticket.TypeId).Name
                //};
                //db.Histories.Add(history);
                if (ticket.AssignedToUserId != null)
                {
                    var notify = new Notification
                    {
                        TicketId = ticket.Id,
                        Message = "Comments has been made for " + ticket.Title,
                        Type = "Comment",
                        ChangeDate = DateTimeOffset.Now,
                        NotifyUserId = ticket.AssignedToUserId
                    };
                    db.Notifications.Add(notify);
                }

                db.Comments.Add(comment);
                
                db.SaveChanges();
                var thisPost = db.Tickets.Find(comment.TicketId);
                if (thisPost != null)
                {
                    return RedirectToAction("Details", "Tickets", new { id = thisPost.Id });// redirect to details page in Blog Post. 
                }
            }

            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", comment.TicketId);
            return RedirectToAction("Index", "Tickets");
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", comment.TicketId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Body,Created,Updated,TicketId,AuthorUserId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", comment.AuthorUserId);
            ViewBag.TicketId = new SelectList(db.Tickets, "Id", "Title", comment.TicketId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KingBugTracker/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KingBugTracker.Models;
using Microsoft.AspNet.Identity;
using KingBugTracker.Models.Helpers;
using System.Threading.Tasks;
using System.Configuration;
using System.Net.Mail;
namespace KingBugTracker.Controllers
{
    public class TicketsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Tickets
        public ActionResult Index()
        {
            var tickets = db.Tickets.Include(t => t.AssignedToUser).Include(t => t.AuthorUser).Include(t => t.Priority).Include(t => t.Project).Include(t => t.Status).Include(t => t.Type);
            return View(tickets.ToList());
        }

        // GET: Tickets/TicketAssign
        [Authorize]
        public ActionResult TicketAssign(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
            ApplicationDbContext context = new ApplicationDbContext();
            Project project = db.Projects.Find(ticket.ProjectId);
            var projectUsers = context.Users.Where(u => u.Projects.Any(p => p.Title == project.Title));
            var role = context.Roles.SingleOrDefault(u => u.Name == "Developer");
            var usersInRole = context.Users.Where(u => u.Roles.Any(r => (r.RoleId == role.Id)));
            var displayUsers = usersInRole.Where(u => u.Projects.Any(p => (p.Title == project.Title)));
            var removeUser = db.Users.Where(u => (u.DisplayName != "N/A" && u.DisplayName != "(Remove Assigned User)"));
            ViewBag.AssignedToUserId = new SelectList(displayUsers, "Id", "DisplayName", ticket.AssignedToUserId);
            return View(ticket);
        }
        // POST: Tickets/TicketAssign
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TicketAssign([Bind(Include = "Id,Title,Body,Created,Updated,ProjectId,TypeId,PriorityId,StatusId,AuthorUserId,AssignedToUserId")] Ticket ticket, string oldAssignedToUserId)
        {
            ApplicationDbContext context = new ApplicationDbContext();
            Project project = db.Projects.Find(ticket.ProjectId);

            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;
                 if (ticket.AssignedToUserId != null)
                {
                    ticket.StatusId = 17;
                    var notify = new Notification
                    {
                        TicketId = ticket.Id,
                        Message = "You have been assigned to " + ticket.Title,
                        Type = "AssignedToUserId",
                        ChangeDate = DateTimeOffset.Now,
                        NotifyUserId = ticket.AssignedToUserId
                    };
                    db.Notifications.Add(notify);
                }

                //15 = unassigned
                //17 = assigned
                
                ApplicationUser NotAssigned = db.Users.FirstOrDefault(u => u.UserName.Equals("unassigned@galileo.com"));
                ApplicationUser RemoveAssigned = db.Users.FirstOrDefault(u => u.UserName.Equals("removeassigned@galileo.com"));
                ticket.Updated = DateTimeOffset.Now;
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            var projectUsers = context.Users.Where(u => u.Projects.Any(p => p.Title == project.Title));
            var role = context.Roles.SingleOrDefault(u => u.Name == "Developer");
            var usersInRole = context.Users.Where(u => u.Roles.Any(r => (r.RoleId == role.Id)));
            var displayUsers = usersInRole.Where(u => u.Projects.Any(p => (p.Title == project.Title)));
            var removeUser = db.Users.Where(u => (u.DisplayName != "N/A" && u.DisplayName != "(Remove Assigned User)"));
            ViewBag.AssignedToUserId = new SelectList(displayUsers, "Id", "DisplayName", ticket.AssignedToUserId);
            return View(ticket);
        }
        // GET: Tickets/Details/5
        public ActionResult Details(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            if (ticket == null)
            {
                return HttpNotFound();
            }
       
                return View(ticket);
        }

        // GET: Tickets/Create
        public ActionResult Create(int id)
        {

            ViewBag.AssignedToUserId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName");
            ViewBag.PriorityId = new SelectList(db.Priorities, "ID", "Name");
            ViewBag.ProjectId = id;
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name");
            ViewBag.TypeId = new SelectList(db.Types, "Id", "Name");
            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Body,Created,Updated,ProjectId,TypeId,PriorityId,StatusId,AuthorUserId,AssignedToUserId")] Ticket ticket, int pId)
        {
            if (ModelState.IsValid)
            {       
                ticket.AuthorUserId = User.Identity.GetUserId();
                ticket.ProjectId = pId;
                ticket.StatusId = 15;
                db.Tickets.Add(ticket);
                ticket.Created = new DateTimeOffset(DateTime.Now);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.AssignedToUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AssignedToUserId);
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AuthorUserId);
            ViewBag.PriorityId = new SelectList(db.Priorities, "ID", "Name", ticket.PriorityId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Title", ticket.ProjectId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", ticket.StatusId);
            ViewBag.TypeId = new SelectList(db.Types, "Id", "Name", ticket.TypeId);
            return View(ticket);
        }

        // GET: Tickets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);

            if (ticket == null)
            {
                return HttpNotFound();
            }

            ViewBag.AssignedToUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AssignedToUserId);
            ViewBag.AuthorUserId = new SelectList(db.Users, "Id", "FirstName", ticket.AuthorUserId);
            ViewBag.PriorityId = new SelectList(db.Priorities, "ID", "Name", ticket.PriorityId);
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Title", ticket.ProjectId);
            ViewBag.StatusId = new SelectList(db.Statuses, "Id", "Name", ticket.StatusId);
            ViewBag.TypeId = new SelectList(db.Types, "Id", "Name", ticket.TypeId);
            return View(ticket);
        }

        // POST: Tickets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Body,Updated,ProjectId,TypeId,PriorityId,StatusId,AuthorUserId,AssignedToUserId")] Ticket ticket)
        {
             if (ModelState.IsValid)
            {
                Ticket oldTicket = new ApplicationDbContext().Tickets.Find(ticket.Id);
                if (oldTicket.PriorityId != ticket.PriorityId)
                {
                    var history = new History
                    {
                        ChangeDate = new DateTimeOffset(DateTime.Now),
                        TicketId = ticket.Id,
                        UserId = User.Identity.GetUserId(),
                        Property = "Priority",
                        OldValue = oldTicket.Priority.Name,
                        NewValue = db.Priorities.Find(ticket.PriorityId).Name
                    };
                    db.Histories.Add(history);
                    var notify = new Notification
                    {
                        TicketId = ticket.Id,
                        Message = "The Priority for " + ticket.Title + "ticket has changed.",
                        Type = "Priority",
                        ChangeDate = DateTimeOffset.Now,
                        NotifyUserId = ticket.AssignedToUserId
                    };
                    db.Notifications.Add(notify);
                    //db.SaveChanges();
                    //notify someone of these changes
                    await Notify(ticket.Id, history);
                }
                if (oldTicket.TypeId != ticket.TypeId)
                {
                    var history = new History
                    {
                        ChangeDate = new DateTimeOffset(DateTime.Now),

KingBugTracker/Views/Tickets/Create.cshtml
@model KingBugTracker.Models.Ticket

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
    <input type="hidden" name="pId" value="@ViewBag.ProjectId" />
    @*@Html.HiddenFor(model => model.Id)*@
    @Html.HiddenFor(model => model.AuthorUserId)
    @*@Html.HiddenFor(model => model.Created)
    @Html.HiddenFor(model => model.Updated)*@
    @*@Html.HiddenFor(model => model.StatusId)*@
    @Html.HiddenFor(model => model.AssignedToUserId)

    @*@Html.HiddenFor(model => model.ProjectId)*@


    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.TypeId, "TypeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PriorityId, "PriorityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PriorityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PriorityId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*@Html.DropDownList("AuthorUserId", null, htmlAttributes: new { @class = "hidden" })*@

        @*@Html.DropDownList("PriorityId", null, htmlAttributes: new { @class = "hidden" })*@


        @*@Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "hidden" })*@
        
        @*@Html.DropDownList("AssignedToUserId", null, htmlAttributes: new { @class = "hidden" })*@








        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KingBugTracker/Views/Tickets/Delete.cshtml
@model KingBugTracker.Models.Ticket

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.AssignedToUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedToUser.FirstName)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.AuthorUser.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AuthorUser.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Project.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Inactivate" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Home")
        </div>
    }
</div>

KingBugTracker/Views/Tickets/Details.cshtml
@model KingBugTracker.Models.Ticket
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ticket</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Priority
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority.Name)
        </dd>

        <dt>
            Project Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.Title)
        </dd>

        <dt>
            Status
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>

        <dt>
            Type
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

        <dt>
            Ticket Title
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            Created
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            Updated
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

    </dl>
</div>

<div class="accordion" id="myAccordion">
    @foreach (var attach in Model.Attachments)
    {
        <p>
            @* button *@
            <button type="button" class="btn btn-default" data-toggle="collapse" data-target="#@attach.Id" data-parent="#myAccordion" style="width:50%">@attach.FileDisplayName</button>
            @* body *@
            <div id="@attach.Id" class="collapse">
                <b>Author:</b> @attach.AuthorUser.DisplayName
                <br /><b>Created:</b> @attach.Created
                <br /><b>Body:</b> @attach.Body
                <br /><b>Attachment:</b> <a href="@attach.FileUrl" target="_blank">@attach.FileUrl</a>
                <br /><b>Preview: </b> <img src="@attach.FileUrl" width="30px" />
            </div>
        </p>
    }
</div>

<a  href="@Url.Action("Create", "Attachments", new { id = Model.Id })" class="btn btn-outline-info" >Create Attachments</a>
<a href="" class="page-scroll btn btn-outline-info" data-toggle="modal" data-target="#history">Ticket History</a>


<hr />
@* Outputing the view  *@
@foreach (var comment in Model.Comments)
{
    var sameUser = User.Identity.GetUserId();
    //From the list,  we are grabbing every 'Comments'
    <div class="comment-form" style="padding: 10px; border:2px solid black;">
        @if (comment.Ticket.AssignedToUser != null)
        {
            <div>
                <h5>@comment.Ticket.AssignedToUser.FirstName</h5>
                <h5>@comment.Created</h5>
            </div>
        }
        else
        {
            <h5>@comment.Ticket.AssignedToUser.Email</h5>
            <h5>@comment.Created</h5>

        }
        <p style="margin-left: 30px">@comment.Body</p>
    </div>
}
@* Comment Box *@
<div class="container">
    @using (Html.BeginForm("Create", "Comments", FormMethod.Post))
    {
        if (Request.IsAuthenticated)
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="TicketId" value="@Model.Id" />
            <div class="row center">
                <div class="form-group">
                    <div class="col-md-12 text-center">
                        <label for="comment-new_textarea" class="sr-only"> Enter your comment</label>
                        <textarea class="form-control text-center" rows="2" id="body" name="body" placeholder="Comment" style="margin:auto"></textarea> <br />
                        <button type="submit" class="btn btn-primary"> Send Comment</button>
                    </div>
                </div>
            </div>
            <br />
        }
    }
</div>
<div class="modal fade" id="history" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h1 class="modal-title" id="myModalLabel"><font color="black">Ticket History</font></h1>
            </div>
            <div class="modal-body col-sm-12">
            @foreach (var history in Model.Histories)
            {
                <div>
                    <b>
                        @history.OldValue changed to @history.NewValue<br>
                    </b>
                    @history.ChangeDate<br>
                </div>
            }
                
            </div>
            <div class="modal-footer no-margin">
            </div>
        </div>
    </div>
</div>



<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index", "Home")
</p>